import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from "@/utils/ReactQueryProvider";
import { AuthProvider, useAuth } from "@/utils/Auth";
import ProtectedRoute from "@/components/ProtectRoute";

export const metadata: Metadata = {
  title: "Raffle Hut",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`h-[100vh] w-[100vw] antialiased`}>
        {" "}
        <ReactQueryProvider>
          <AuthProvider>
            <ProtectedRoute>{children}</ProtectedRoute>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
